version: "3.9"
services:
  lava-server:
    build: .
    image: seojikim/amd64-lava-server
    container_name: lava-server
    ports:
      - "9090:80"
      #- "5555:5500"
      - "5557:5555"
      - "5558:5556"
    #volumes:
    networks:
      - my_net
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    privileged: true

networks:
  my_net:
    external: true
