version: "3.9"
services:
  lava-dispatcher:
    #build: .
    image: lavasoftware/amd64-lava-dispatcher
    container_name: lava-dispatcher
    ports:
      #- "9090:80"
      - "5555:5555"
      - "5556:5556"
    volumes:
      - /boot:/boot
      - /lib/modules:/lib/modules
      - /dev/bus/usb:/dev/bus/usb
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - my_net
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    privileged: true
    environment:
      - URL=http://10.157.133.51
      - LOGGER_URL=tcp://10.157.133.51:5557
      - MASTER_URL=tcp://10.157.133.51:5558
      - DISPATCHER_HOSTNAME=--hostname=lava-dispatcher
      - WORKER_NAME=--name lava-dispatcher
      - TOKEN=--token O206iu3A4QkxrGSqc0yxSWLYOaIH9t1P
    #command: /sbin/init

networks:
  my_net:
    external: true
